// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHKQK30qD-buFGC6D9bKprJtK1VijhVU',
    appId: '1:222126078513:web:da96a10622db392d19b310',
    messagingSenderId: '222126078513',
    projectId: 'kream-132e4',
    authDomain: 'kream-132e4.firebaseapp.com',
    storageBucket: 'kream-132e4.firebasestorage.app',
    measurementId: 'G-ZLKPEB196L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnvOHZTgVLouHAPugC3hNCQKgOro4R4uU',
    appId: '1:222126078513:android:6f0f2f427cce50b919b310',
    messagingSenderId: '222126078513',
    projectId: 'kream-132e4',
    storageBucket: 'kream-132e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1G7FDI9zjCYwf3YwR6wZmmj_eeiF372I',
    appId: '1:222126078513:ios:eecd36117b431a5a19b310',
    messagingSenderId: '222126078513',
    projectId: 'kream-132e4',
    storageBucket: 'kream-132e4.firebasestorage.app',
    iosBundleId: 'com.example.kream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1G7FDI9zjCYwf3YwR6wZmmj_eeiF372I',
    appId: '1:222126078513:ios:eecd36117b431a5a19b310',
    messagingSenderId: '222126078513',
    projectId: 'kream-132e4',
    storageBucket: 'kream-132e4.firebasestorage.app',
    iosBundleId: 'com.example.kream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrHKQK30qD-buFGC6D9bKprJtK1VijhVU',
    appId: '1:222126078513:web:0c67b9ca3ea6223119b310',
    messagingSenderId: '222126078513',
    projectId: 'kream-132e4',
    authDomain: 'kream-132e4.firebaseapp.com',
    storageBucket: 'kream-132e4.firebasestorage.app',
    measurementId: 'G-ZDWZS8VSC7',
  );
}
